### ISSUE TITLE
Odd read behaviour of NA write

### ISSUE THREAD

**Issue by rsbivand** [edzer/sfr#309] opened 2017-04-20 19:11 UTC
Started as a bug report on foreign::write.dbf() ex-shapelib last century, suggested (if shapefile) using OGR/GDAL in rgdal or sf:

```
library(rgdal)
sp <- SpatialPointsDataFrame(SpatialPoints(cbind(0,0),
proj4string=CRS("+proj=longlat")), data=data.frame(x=as.numeric(NA)))
summary(sp$x)
tf <- tempfile()
writeOGR(sp, dsn=tf, layer=basename(tf), driver="ESRI Shapefile")
readLines(paste0(tf, "/", basename(tf), ".dbf"))
ogrInfo(dsn=tf, layer=basename(tf))
summary(readOGR(dsn=tf, layer=basename(tf))$x)
tf <- tempfile()
writeOGR(sp, dsn=tf, layer=basename(tf), driver="GPKG")
ogrInfo(dsn=tf, layer=basename(tf))
summary(readOGR(dsn=tf, layer=basename(tf))$x)
```

which will not round-trip and convert the written NA/missing to zero. Try sf:

```
library(sf)
tf <- tempfile()
st <- st_as_sf(sp)
st
summary(st$x)
st_write(st, dsn=paste0(tf, ".gpkg"), driver="GPKG")
st1 <- st_read(dsn=paste0(tf, ".gpkg"))
summary(st1$x)
```
which does the same. Is the written value in the SQLite file right:

```
library(RSQLite)
mydb <- dbConnect(RSQLite::SQLite(), paste0(tf, ".gpkg"))
summary(dbReadTable(mydb, dbListTables(mydb)[1])$x)
dbDisconnect(mydb)
```

yes it is. Can we write a numeric NA out and read it back in again?

**Comment by edzer** [comment] 2017-04-20 19:25
Looks to me like we can.

**Comment by rsbivand** [comment] 2017-04-21 07:47
On GDAL 2.1.3, I agree, but what I tried yesterday evening was on GDAL 2.2.0beta1,

**Comment by rsbivand** [comment] 2017-04-21 07:51
On 2.1.3:

```
> library(rgdal)
Loading required package: sp
rgdal: version: 1.2-6, (SVN revision 651)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.1.3, released 2017/20/01
 Path to GDAL shared files: /usr/local/share/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.2-4 
> sp <- SpatialPointsDataFrame(SpatialPoints(cbind(0,0),
+ proj4string=CRS("+proj=longlat")), data=data.frame(x=as.numeric(NA)))
> summary(sp$x)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
> tf <- tempfile()
> writeOGR(sp, dsn=tf, layer=basename(tf), driver="ESRI Shapefile")
> readLines(paste0(tf, "/", basename(tf), ".dbf"))
[1] "\003u\004\025\001"         " ************************"
Warning messages:
1: In readLines(paste0(tf, "/", basename(tf), ".dbf")) :
  line 1 appears to contain an embedded nul
2: In readLines(paste0(tf, "/", basename(tf), ".dbf")) :
  incomplete final line found on '/tmp/Rtmp7a7PK9/filef8528489e7a/filef8528489e7a.dbf'
> ogrInfo(dsn=tf, layer=basename(tf))
Source: "/tmp/Rtmp7a7PK9/filef8528489e7a", layer: "filef8528489e7a"
Driver: ESRI Shapefile; number of rows: 1 
Feature type: wkbPoint with 2 dimensions
Extent: (0 0) - (0 0)
CRS: +proj=longlat +ellps=WGS84 +no_defs  
LDID: 87 
Number of fields: 1 
  name type length typeName
1    x    2     24     Real
> summary(readOGR(dsn=tf, layer=basename(tf))$x)
OGR data source with driver: ESRI Shapefile 
Source: "/tmp/Rtmp7a7PK9/filef8528489e7a", layer: "filef8528489e7a"
with 1 features
It has 1 fields
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
> tf <- tempfile()
> writeOGR(sp, dsn=tf, layer=basename(tf), driver="GPKG")
> ogrInfo(dsn=tf, layer=basename(tf))
Source: "/tmp/Rtmp7a7PK9/filef85776f1007", layer: "filef85776f1007"
Driver: GPKG; number of rows: 1 
Feature type: wkbPoint with 2 dimensions
Extent: (0 0) - (0 0)
CRS: +proj=longlat +datum=WGS84 +no_defs  
Number of fields: 1 
  name type length typeName
1    x    2      0     Real
> summary(readOGR(dsn=tf, layer=basename(tf))$x)
OGR data source with driver: GPKG 
Source: "/tmp/Rtmp7a7PK9/filef85776f1007", layer: "filef85776f1007"
with 1 features
It has 1 fields
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
> library(sf)
Linking to GEOS 3.6.1, GDAL 2.1.3, proj.4 4.9.3
> tf <- tempfile()
> st <- st_as_sf(sp)
> st
Simple feature collection with 1 feature and 1 field
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 0 ymax: 0
epsg (SRID):    4326
proj4string:    +proj=longlat +ellps=WGS84 +no_defs
   x   geometry
1 NA POINT(0 0)
> summary(st$x)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
> st_write(st, dsn=paste0(tf, ".gpkg"), driver="GPKG")
Writing layer `filef8576e6dca1.gpkg' to data source `/tmp/Rtmp7a7PK9/filef8576e6dca1.gpkg' using driver `GPKG'
features:       1
fields:         1
geometry type:  Point
> st1 <- st_read(dsn=paste0(tf, ".gpkg"))
Reading layer `filef8576e6dca1.gpkg' from data source `/tmp/Rtmp7a7PK9/filef8576e6dca1.gpkg' using driver `GPKG'
converted into: POINT
Simple feature collection with 1 feature and 1 field
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 0 ymax: 0
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
> summary(st1$x)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
```

**Comment by edzer** [comment] 2017-04-21 08:05
I can reproduce the rgdal using svn, but using a fresh git checkout of sf I see
```r
> library(sf)
> tf <- tempfile()
> st <- st_as_sf(sp)
> st
Simple feature collection with 1 feature and 1 field
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 0 ymax: 0
epsg (SRID):    4326
proj4string:    +proj=longlat +ellps=WGS84 +no_defs
   x   geometry
1 NA POINT(0 0)
> summary(st$x)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
> st_write(st, dsn=paste0(tf, ".gpkg"), driver="GPKG")
Writing layer `file16ab240d5ef1.gpkg' to data source `/tmp/RtmpuA1beC/file16ab240d5ef1.gpkg' using driver `GPKG'
features:       1
fields:         1
geometry type:  Point
> st1 <- st_read(dsn=paste0(tf, ".gpkg"))
Reading layer `file16ab240d5ef1.gpkg' from data source `/tmp/RtmpuA1beC/file16ab240d5ef1.gpkg' using driver `GPKG'
converted into: POINT
Simple feature collection with 1 feature and 1 field
geometry type:  POINT
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 0 ymax: 0
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
> summary(st1$x)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA       1 
> sf_extSoftVersion()
          GEOS           GDAL         proj.4         lwgeom 
       "3.5.1"   "2.2.0beta1"        "4.9.2" "2.3.2 r15302" 
```
is it because of [this](https://github.com/edzer/sfr/blob/master/src/gdal_read.cpp#L241-L243)?

**Comment by rsbivand** [comment] 2017-04-21 09:55
[In sf for read resolved here](https://github.com/edzer/sfr/commit/ec5a48d41f19f4c2a11177c053b7c036aec927db#diff-e837d2657fdd4875a8da6732281b3bd6); in rgdal for read/write resolved [here](https://r-forge.r-project.org/scm/viewvc.php?view=rev&root=rgdal&revision=658)

**Comment by edzer** [comment] 2017-04-21 10:53
As of the changes in rgdal: didn't try but think they assume gdal major >= 2 and will break for gdal 1.x where x >= 2. If you'd want to remove gdal 1.x compatibility, that would clean up a lot of code!

**Comment by rsbivand** [comment] 2017-04-21 10:58
Thanks, I'll check but cannot remove < 2 because major Linux distributions aren't there yet; Debian Jessie is at 1.10.

**Comment by rsbivand** [comment] 2017-04-21 14:28
Now have:

```
#if ((GDAL_VERSION_MAJOR == 2 && GDAL_VERSION_MINOR >= 2) || GDAL_VERSION_MAJOR > 2)
```

but cannot rebuild 1.11.2, as my g++ is now too new and I can't find the incantation to make g++ adhere to the standard from then. Does the macro look logical?

**Comment by edzer** [comment] 2017-04-21 14:34
Time for docker. Macro looks good; I'd trust it blindly.

**Comment by rsbivand** [comment] 2017-04-24 09:16
Please show me a link showing how to install (apt-get??) the external dependencies in a debian stable image, then R, then find out how to run R CMD check including the relevant compilers. I did listen to Dirk two years ago, but never got past starting R-base in a rocker image.

**Comment by edzer** [comment] 2017-04-24 09:28
`apt-get install docker`, then I would use [this](https://github.com/rocker-org/geospatial/tree/master/3.3.3) Dockerfile, remove [this](https://github.com/rocker-org/geospatial/blob/master/3.3.3/Dockerfile#L37-L68), uncomment [this](https://github.com/rocker-org/geospatial/blob/master/3.3.3/Dockerfile#L10), remove [sf](https://github.com/rocker-org/geospatial/blob/master/3.3.3/Dockerfile#L90), save in a new directory (NOT under /tmp) and run

    docker build . --tag rgdal

next, run the image by

    docker run -ti rgdal /bin/bash

download `rgdal` source from r-forge, build, test.

adding `--rm` to the last command removes the image (and the work you did in it) when you exit. I always do that.

**Comment by rsbivand** [comment] 2017-04-24 12:11
OK, thanks - current rgdal checks cleanly with Jessie/Stable GDAL 1.10.1, and following installation round-trips NAs.

**Comment by edzer** [comment] 2017-04-24 12:48
Close this issue?

**Closed** 2017-04-24 12:49 UTC
