### ISSUE TITLE
st_area failure on group_by

### ISSUE THREAD

**Issue by jamgreen** [edzer/sfr#302] opened 2017-04-14 02:01 UTC
st_area will fail on a sf that is a grouped_df.

the logic for this is sound but the error:
`Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index` 

is quite cryptic. Would it be possible to offer a more informative error for those who seek to apply sf functions to grouped dfs?

**Comment by edzer** [comment] 2017-04-14 06:54
Could you provide a reproducible example, using for instance `nc`? This worked:
```r
library(sf)
library(dplyr)
demo(nc)
x = group_by(nc, c(rep(1,50),rep(2,50)))
st_area(x)
```

**Comment by Nowosad** [comment] 2017-04-14 12:20
`mutate()` with `st_area()` fails:

```
library(sf)
library(dplyr)
demo(nc)
x = group_by(nc, c(rep(1,50), rep(2,50))) %>% 
        mutate(area = st_area(.))
```

**Comment by tim-salabim** [comment] 2017-04-14 13:08
It works when you `summarise()` before `mutating`
```r
nc %>%
  group_by(c(rep(1,50), rep(2,50))) %>%
  summarize() %>%
  mutate(area = st_area(.))
```

**Comment by Nowosad** [comment] 2017-04-14 13:16
Good point @tim-salabim. However, shouldn't it also work like that?

```
nc %>%
        group_by(c(rep(1,50), rep(2,50))) %>%
        summarize(area = st_area(.))
```

**Comment by edzer** [comment] 2017-04-19 19:31
using dplyr 0.6, I see
```r
> nc %>%
+         group_by(c(rep(1,50), rep(2,50))) %>%
+         summarize(area = st_area(.))
Error in summarise_impl(.data, dots) : 
  Column `area`: must be length one (a summary value), not 100
```
@Nowosad , could you please explain to me what, in this context, `st_area` should have returned that has length one?

**Comment by edzer** [comment] 2017-04-23 10:04
I think you want sth like this:
```r
nc %>% 
  mutate(area = st_area(.)) %>% 
  group_by(c(rep(1,20), rep(2,80)))  %>% 
  summarize(area = sum(area))
Simple feature collection with 2 features and 2 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
# A tibble: 2 × 3
  `c(rep(1, 20), rep(2, 80))`             area              geom
                        <dbl>      <S3: units>  <simple_feature>
1                           1  22022914217 m^2 <MULTIPOLYGON...>
2                           2 105008842929 m^2 <MULTIPOLYGON...>
```

I can understand you would like something like this to give group areas:
```r
> nc %>% group_by(c(rep(1,50), rep(2,50))) %>%  summarize(area = sum(st_area(.)))
Simple feature collection with 2 features and 2 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
epsg (SRID):    4267
proj4string:    +proj=longlat +datum=NAD27 +no_defs
# A tibble: 2 × 3
  `c(rep(1, 50), rep(2, 50))`             area              geom
                        <dbl>      <S3: units>  <simple_feature>
1                           1 127031757146 m^2 <MULTIPOLYGON...>
2                           2 127031757146 m^2 <MULTIPOLYGON...>
```
but it doesn't. I tried a similar thing with `mtcars`:
```r
> fn = function(x) sqrt(x$disp)
> mtcars %>%
+ group_by(cyl) %>%
+ summarise(fn = mean(fn(.)))
# A tibble: 3 × 2
    cyl       fn
  <dbl>    <dbl>
1     4 14.63171
2     6 14.63171
3     8 14.63171
```
which convinced me that the cause for this _not_ giving group means (whether intentionally or unintentionally) is 100% with `dplyr`, not with `sf`. Hence, I close it here.

**Closed by edzer** 2017-04-23 10:04 UTC
