### ISSUE TITLE
cbind of sf and df

### ISSUE THREAD

**Issue by faridcher** [edzer/sfr#92] opened 2016-12-02 20:30 UTC
Hi all,
cbind of a sf and a data.frame creates a weird matrix object.
`dd <- cbind(sf,df)`

but if we do it this way it works:
```r
dd <- st_sf(data.frame(sf,df))
```

as `cbind.sf` does the above procedure internally, I think with a minor change, `cbind.sf` could become more flexible.

**Comment by edzer** [comment] 2016-12-08 20:29
Please try a pull request, it is hard for me to see what you suggest to change otherwise.

**Comment by faridcher** [comment] 2016-12-09 07:58
It turns out the problem is not from sf rather the way cbind dispatch on `sf` object:

```r
sf <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
df <- data.frame( field1=1:nrow(nc) , field2=1:nrow(nc))

weird_obj <- cbind(sf,df)
new_sf <- cbind.sf(sf,df)  #works
```

`cbind` is an internal generic function and I don't understand why `cbind` has this behaviour!

**Comment by edzer** [comment] 2016-12-09 11:25
Since it doesn't have named arguments before ..., it can't use standard method dispatch.

**Comment by faridcher** [comment] 2016-12-11 16:12
any workaround?

**Comment by edzer** [comment] 2016-12-11 16:54
call `cbind.sf` directly?

**Comment by etiennebr** [comment] 2017-01-05 14:54
dplyr has `bind_rows()` and `bind_cols()`, maybe `sf` could use a similar interface, or something like `sf_bind_rows()` and `sf_bind_cols()` with a similar set of strict conditions ?

**Comment by edzer** [comment] 2017-01-12 08:51
`base:::rbind` works for binding rows of `sf` objects, and `cbind.sf` or `dplyr:::bind_cols` work for binding columns. Do we need other aliases for the `cbind` case, or for both, in order to hide this from the user (as @etiennebr suggests)?

**Comment by faridcher** [comment] 2017-01-12 18:15
I don't think additional aliases are necessary. Using old known interfaces such as `cbind` is more intuitive and faster to grab for the end user. However, I think `cbind.sf` should be documented, because not all R users are aware of method dispatching of the R.  I am not a user of `dplyr`, but if that `bind_cols` function is not exported (which is evident from the notation), an alias would be appropriate. again, because not everybody know how to access a `non-exported` function!

**Comment by edzer** [comment] 2017-02-26 20:34
`cbind` and `rbind` methods seem to work; can we close this?

**Comment by faridcher** [comment] 2017-02-27 01:13
Still not working. cbind (sf,df) creates an object of class matrix, with mode of list.

**Comment by edzer** [comment] 2017-02-27 09:31
But `rbind(sf,sf)` work, right? 

For `cbind`, I suggest to export a `st_bind_cols` that explicitly calls `sf:::cbind.sf`, then.

**Comment by faridcher** [comment] 2017-02-27 19:27
for `rbind(sf,sf)`, it works fine. `st_bind_cols ` is better than the cryptic `cbind.sf` .

**Closed** 2017-02-27 19:50 UTC

**Comment by edzer** [comment] 2017-04-29 16:41
`dplyr::bind_cols` now works with `sf` and non-`sf` objects, but this might only be true for the (pre) 0.6.0 version on github.com/tidyverse/

**Comment by faridcher** [comment] 2017-05-07 21:34
make it work also with `sfc` (i.e. sfc is passed instead of sf):

```st_bind_cols(st_sfc(st_point(c(1,1)))  , a= 1, data.frame(b=2)   )``` 

> Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class "c("sfc_POINT", "sfc")" to a data.frame

The following change is needed:

```r
st_bind_cols <- function (...)
{
  arg1 <- list(...)[[1]]

  if (inherits(arg1,"sf"))
    cbind.sf(...)
  else if(inherits(arg1,"sfc"))
    cbind.sfc(...)
}
cbind.sfc <- function(...){
  sf::st_sf(...)
}
st_bind_cols( st_sfc(st_point(c(1,1)))  , a= 1, data.frame(b=2)   )
```

**Comment by edzer** [comment] 2017-05-08 06:08
The better approach might be to add
```r
as.data.frame.sfc = function(x, ...) {
    ret = data.frame(row.names = seq_along(x))
    ret$geometry = x
    ret
}
```

**Comment by eivindhammers** [comment] 2017-10-11 10:56
`dplyr::bind_cols(sf, data.frame)` works, but is sub-optimal because it doesn't put columns from `data.frame` before the geometry column, which I expected. Is this intended behavior? MWE:
```R
sf <- st_read(system.file("shape/nc.shp", package="sf"), "nc", crs = 4267)
df <- data.frame(field1 = 1:nrow(sf) , field2 = 1:nrow(sf))

new_sf <- dplyr::bind_cols(sf, df)
names(new_sf)

 [1] "AREA"      "PERIMETER" "CNTY_"     "CNTY_ID"   "NAME"      "FIPS"      "FIPSNO"    "CRESS_ID"  "BIR74"     "SID74"     "NWBIR74"   "BIR79"     "SID79"    
[14] "NWBIR79"   "geometry"  "field1"    "field2" 
```

**Comment by edzer** [comment] 2017-10-11 12:54
Why does the order of columns matter? I would expect `bind_cols` to keep them in the order of appearance.

**Comment by eivindhammers** [comment] 2017-10-11 13:09
It matters for example when viewing `sf`-objects in RStudio environment pane, or `print()`-ing them, since you're usually not interesting in looking directly at the geometry column in those cases. Also, I thought that `sf` convention was to have the geometry column last?

**Comment by edzer** [comment] 2017-10-11 13:40
sounds like a GUI issue rather than an R issue. Sinds `bind_cols` is not a generic, there is nothing `sf` can do for you, AFAICT.
