### ISSUE TITLE
Misleading warning 

### ISSUE THREAD

**Issue by Nowosad** [edzer/sfr#306] opened 2017-04-17 23:48 UTC
In the last few weeks, I've came across this warning message when I've been writing data to .shp file - ` Value [SOME_VALUE] of field big_number of feature [SOME_VALUE] not successfully written. Possibly due to too larger number with respect to field width`. However, a new file (and a new object) looks the same as the old one. Reproducible example below:

```R
> nc = st_read(system.file("shape/nc.shp", package="sf"), quiet = TRUE)
> nc$big_number = seq(100000, 9900100000, 100000000)
> st_write(nc, 'nc2.shp')
Writing layer `nc2.shp` to data source `nc2.shp` using driver `ESRI Shapefile`
features:       100
fields:         15
geometry type:  Multi Polygon
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()[1]
Warning message:
In CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  ... :
  GDAL Message 1: Value 100100000 of field big_number of feature 1 not successfully written. Possibly due to too larger number with respect to field width
> nc2 = st_read('nc2.shp', quiet = TRUE)
> identical(nc$big_number, nc2$big_number)
[1] TRUE
```

**Comment by edzer** [comment] 2017-04-19 19:25
The warning is emitted by gdal, not by `sf`; I could silence the warning generator before writing, but that would also suppress helpful warnings, maybe not such a good idea.

Does this also occur when you write to GPKG? (we live in post-shapefile era)

**Comment by Nowosad** [comment] 2017-04-19 21:00
Nope, it works fine with GPKG. 
Btw - I want to think that we live in a post-shapefile era, but probably it's still way ahead...

**Comment by edzer** [comment] 2017-04-19 21:13
It's up to you.

**Comment by edzer** [comment] 2017-04-19 21:19
`rgdal::writeOGR` gives the same warnings; there's little we can do in R to ease the pain caused by shapefiles.

**Comment by edzer** [comment] 2017-04-23 09:35
This is a [known problem of the GDAL shapefile driver](https://trac.osgeo.org/gdal/ticket/6803), hence I close it here.

**Closed by edzer** 2017-04-23 09:35 UTC
