### ISSUE TITLE
liblwgeom support on macOS

### ISSUE THREAD

**Issue by pat-s** [edzer/sfr#349] opened 2017-05-18 08:03 UTC
Related: #347, #266 

I did `brew install liblwgeom && brew link --force liblwgeom` and during `sf` source install `liblwgeom` is found. However, ` lwgeom_version in -llwgeom` is not found. 

```
checking liblwgeom.h usability... yes
checking liblwgeom.h presence... yes
checking for liblwgeom.h... yes
checking for lwgeom_version in -llwgeom... no
```

`sf` v0.4.3

Any ideas where to look here? I do not know where `-llwgeom` is referring to..

**Comment by edzer** [comment] 2017-05-18 08:09
My guess is that the version of lwgeom is too old, but I haven't tried or looked into.

**Comment by pat-s** [comment] 2017-05-18 08:23
* brew: 2.1.5_3 (Dec 2013) 
* latest postgis: 2.3.2
* Debian 9: 2.3.0 (Sep 2016)

It seems patching the brew formula might not be that easy -> `brew edit liblwgeom` 10-13:

> Strip all the PostgreSQL functions from PostGIS configure.ac, to allow
>     building liblwgeom.dylib without needing PostgreSQL
>     NOTE: this will need to be maintained per postgis version
>     Somehow, this still works for 2.1.5, which is awesome!

**Comment by edzer** [comment] 2017-05-18 08:34
I see, on ubuntu 16.04:
```r
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.1.3, proj.4 4.9.2, lwgeom 2.3.2 r15302
```
(seems that lwgeom versions follow postgis version)

**Comment by pat-s** [comment] 2017-05-18 08:47
> (seems that lwgeom versions follow postgis version)

jep, its dev repository is within the postgis one: https://github.com/postgis/postgis/tree/svn-trunk/liblwgeom

**Comment by edzer** [comment] 2017-05-18 08:50
So we can close this one, right?

**Comment by pat-s** [comment] 2017-05-18 08:56
I would like to leave it open until there is a working solution for the `liblwgeom` install - the current brew version does not work (probably its too old as you suggested). I will later try to install from source / patch the brew formula. 

ping @bhaskarvk

**Comment by edzer** [comment] 2017-05-18 09:00
I like to see open issues as issues that need work on the side of `sf`. As this is an issue with brew and MacOS, I'm closing here, but would welcome it if you report back here when you've settled that.

**Closed by edzer** 2017-05-18 09:00 UTC

**Comment by pat-s** [comment] 2017-05-18 19:05
`brew install postgis` solves the problem as it does the linking to `-llwgeom`

```
checking liblwgeom.h usability... yes
checking liblwgeom.h presence... yes
checking for liblwgeom.h... yes
checking for lwgeom_version in -llwgeom... yes
```

I also checked that `st_make_valid()`  is working.

It would be good if a message could be thrown that it depends on `brew install postgis` if one tries to use `st_make_valid()` on macOS.  Currently it looks likes this: 

```
st_make_valid(poly) -> poly_V
Error in CPL_make_valid(x) :
  st_make_valid requires compilation against liblwgeom
```

and if one does `brew install liblwgeom` it will not work. So the current message is right in terms of dependency but misleading when one wants to solve the issue -> see PR #350

**Comment by NateMietk** [comment] 2017-09-15 21:19
I successfully installed using `brew install postgis`, but I still generate the `Error in CPL_make_valid(x) :
  st_make_valid requires compilation against liblwgeom` error.  I have confirmed that I have `liblwgeom` installed and have reinstalled `sf`, nothing seems to be working.  Any suggestions here?

**Comment by pat-s** [comment] 2017-09-15 21:34
Works for me. Do you have different settings?

```r
devtools::session_info("sf")
Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin16.7.0        
 ui       RStudio (1.1.362)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2017-09-15                  

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 DBI         0.7     2017-06-18 CRAN (R 3.4.0)
 graphics  * 3.4.1   2017-08-18 local         
 grDevices * 3.4.1   2017-08-18 local         
 grid        3.4.1   2017-08-18 local         
 magrittr    1.5     2014-11-22 CRAN (R 3.3.2)
 methods   * 3.4.1   2017-08-18 local         
 Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)
 sf        * 0.5-4   2017-08-28 CRAN (R 3.4.1)
 stats     * 3.4.1   2017-08-18 local         
 tools       3.4.1   2017-08-18 local         
 udunits2    0.13    2016-11-17 CRAN (R 3.3.2)
 units       0.4-6   2017-08-27 CRAN (R 3.4.1)
 utils     * 3.4.1   2017-08-18 local       
```  

```r
Linking to GEOS 3.6.2, GDAL 2.2.1, proj.4 4.9.3, lwgeom 2.3.2 r15302

x = st_sfc(st_polygon(list(rbind(c(0,0),c(0.5,0),c(0.5,0.5),c(0.5,0),c(1,0),c(1,1),c(0,1),c(0,0)))))
st_make_valid(x)

Geometry set for 1 feature 
geometry type:  GEOMETRYCOLLECTION
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
epsg (SRID):    NA
proj4string:    NA
GEOMETRYCOLLECTION (POLYGON ((0.5 0, 0 0, 0 1, ...
```

**Comment by NateMietk** [comment] 2017-09-15 21:46
my `devtools::session_info("sf")` shows the same information:

`Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Denver              
 date     2017-09-15                  

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 DBI         0.7     2017-06-18 CRAN (R 3.4.0)
 graphics  * 3.4.1   2017-07-07 local         
 grDevices * 3.4.1   2017-07-07 local         
 grid        3.4.1   2017-07-07 local         
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)
 methods   * 3.4.1   2017-07-07 local         
 Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)
 sf          0.5-4   2017-08-28 CRAN (R 3.4.1)
 stats     * 3.4.1   2017-07-07 local         
 tools       3.4.1   2017-07-07 local         
 udunits2    0.13    2016-11-17 CRAN (R 3.4.0)
 units       0.4-6   2017-08-27 CRAN (R 3.4.1)
 utils     * 3.4.1   2017-07-07 local     `

Using your example I generate the same `Error in CPL_make_valid(x) : 
  st_make_valid requires compilation against liblwgeom`

**Comment by pat-s** [comment] 2017-09-15 22:09
A possible error source could be that you are not running macOS Sierra but El Capitan as far as I can see?

Did `sf` successfully compile against `liblwgeom`during installation?


```
install.packages("sf")
[...]
checking liblwgeom.h usability... yes
checking liblwgeom.h presence... yes
checking for liblwgeom.h... yes
checking for lwgeom_version in -llwgeom... yes
```

**Comment by NateMietk** [comment] 2017-09-15 22:13
Doesn't look that way. I didn't think OS Sierra would have made a difference!  

```
Installing package into ‘/Users/nami1114/Library/R/3.4/library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/sf_0.5-4.tgz'
Content type 'application/x-gzip' length 35969512 bytes (34.3 MB)
==================================================
downloaded 34.3 MB


The downloaded binary packages are in
	/var/folders/jw/l23y3f2j7m7b5mchg3mdg8g87kc8gr/T//RtmpYl7luO/downloaded_packages
```

**Comment by pat-s** [comment] 2017-09-16 10:28
> I'll just use a docker container until Sierra is compatible with sf. 

Don't understand what you mean. `sf` is compatible with Sierra. However, there are problems on El Capitan obviously. 

Try to explicitly install from source and not use the binary: `install.packages("sf", type="source")`

**Comment by NateMietk** [comment] 2017-09-20 21:23
Sorry.  Misunderstood.  I am using macOS Sierra, NOT El Captain.  The install from the source does not work, thanks for the suggestion.  

I have been using a docker container in the meantime to get around this issue.

**Comment by pat-s** [comment] 2017-09-20 21:59
Did you update your system since your last post? Your `sessionInfo()` output tells that you are running ElCapitan:

` system   x86_64, darwin15.6.0`

Sierra has `darwin16.x.x`.

Also, the logs of the source installation (`install.packages(sf)`) would be helpful here.

**Comment by NateMietk** [comment] 2017-09-20 22:04
hmm no, I updated the system (both of the machines I am trying to run sf on) last year when it was released.  

```
> install.packages("sf", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/sf_0.5-4.tar.gz'
Content type 'application/x-gzip' length 4932624 bytes (4.7 MB)
==================================================
downloaded 4.7 MB

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/d5/gp03lxfx5n56_hn4wdmkdmvm0000gn/T/RtmpGguQ1p/downloaded_packages’
```

**Comment by pat-s** [comment] 2017-09-20 22:08
its not about `liblwgeom`at all but your gdal config is not properly setup.

Follow the instructions of the README: 

```
brew unlink gdal
brew tap osgeo/osgeo4mac && brew tap --repair
brew install proj
brew install geos
brew install udunits
brew install gdal2 --with-armadillo --with-complete --with-libkml --with-unsupported
brew link --force gdal2
```
