### ISSUE TITLE
Please consider implementing st_makevalid

### ISSUE THREAD

**Issue by onehundredpercenttexan** [edzer/sfr#67] opened 2016-11-10 17:48 UTC
I've searched many times over the years for an R version of postgis'  `st_makevalid()` function _(via_ [liblwgeom](https://github.com/postgis/postgis/tree/svn-trunk/liblwgeom)) and wonder if this would be a good time and place for it. Thanks for all your hard work!

**Comment by tiernanmartin** [comment] 2016-11-10 18:12
I'll second that. 

I have frequently resorted to pre-processing spatial data in GRASS (via [rgrass7](https://cran.r-project.org/web/packages/rgrass7/index.html)) because there isn't a good R implementation of `makevalid`. While this usually resolves my issue, the installation and setup of GRASS is non-trivial (esp. for Mac users) and it detracts from the reproducibility of an analysis.

**Comment by edzer** [comment] 2016-11-10 19:45
It's definitely out of scope for this project, and would require additional packages on [all CRAN check serves](http://statmath.wu.ac.at/AASC/debian/binary-amd64/Packages). But surely a nice idea!

**Comment by rsbivand** [comment] 2016-11-10 19:50
Does [cleangeo](https://cran.r-project.org/package=cleangeo) go in that direction? Maybe helping Emmanuel with enabling or duplicating this for sf is a better way forward than making sf too big?

**Comment by edzer** [comment] 2016-11-20 22:12
More realistically, @onehundredpercenttexan , where is the stand-alone lwgeom library to which one could possibly link? Your link seems to points to a component of PostGIS.

**Comment by onehundredpercenttexan** [comment] 2016-11-23 17:02
I was under the impression that there were changes made to lwgeom that allow for somewhat standalone use:
https://github.com/postgis/postgis/pull/6

**Comment by edzer** [comment] 2016-12-19 21:49
Is the [RT Topology Library](https://strk.kbt.io/projects/rttopo/index.html) what you had in mind?

**Comment by edzer** [comment] 2017-03-07 18:38
Some good news to be reported here: we have `sf` now autodeting `lwgeom`, and if present provide a working `st_make_valid`:
```r
> library(sf)
Linking to GEOS 3.5.0, GDAL 2.1.3, proj.4 4.9.2, lwgeom 2.2.1 r14555
> x = st_sfc(st_polygon(list(rbind(c(0,0),c(0.5,0),c(0.5,0.5),c(0.5,0),c(1,0),c(1,1),c(0,1),c(0,0)))))
> st_is_valid(x)
[1] FALSE
Warning message:
In eval(substitute(expr), envir, enclos) :
  Self-intersection at or near point 0.5 0
> y = st_make_valid(x)
> st_is_valid(y)
[1] TRUE
> y
Geometry set for 1 feature 
geometry type:  GEOMETRYCOLLECTION
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
epsg (SRID):    NA
proj4string:    NA
GEOMETRYCOLLECTION(POLYGON((0.5 0, 0 0, 0 1, 1 ...
> y %>% st_cast()
Geometry set for 2 features 
geometry type:  GEOMETRY
dimension:      XY
bbox:           xmin: 0 ymin: 0 xmax: 1 ymax: 1
epsg (SRID):    NA
proj4string:    NA
POLYGON((0.5 0, 0 0, 0 1, 1 1, 1 0, 0.5 0))
LINESTRING(0.5 0, 0.5 0.5)
> 
```
I render it quite unlikely that there will be support for `lwgeom` on CRAN, i.e. in the binary versions distributed there for Windows and Mac, any time soon. If there are other things in `lwgeom` useful for sf, let me know.

**Closed** 2017-04-27 21:29 UTC

**Comment by Demetrio92** [comment] 2018-04-20 13:09
@edzer Somehow I don't get if this is actualy a *wontfix*, or if it is *fixed*. 
I just installed the latest version via `devtools::install_github("r-spatial/sf")`, but `st_make_valid` doesn't seem to be a part of the package. 
Any way I can get it?

Thanks!

**Comment by rsbivand** [comment] 2018-04-20 13:12
`st_make_valid()` is in **lwgeom** on CRAN, including Windows and OSX binaries.

**Comment by Demetrio92** [comment] 2018-04-20 13:27
@rsbivand so it is actually a desired behaviour that although I have `lwgeom` and `r-spatial/lwgeom` `sf` doesn't automatically connect to it? [in the example above provided by @edzer it does]

```R
> library(sf)
Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
> library(lwgeom)
Linking to liblwgeom 2.4.2 r16113, GEOS 3.5.1, proj.4 4.9.2
```

Anyways, it is working, thanks a lot! Especially for a super quick reply
